# Generated by Django 5.1 on 2024-11-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="secret_info",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
