# Generated by Django 5.1 on 2024-10-09 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_delete_posttag"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.post"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tag"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["post", "tag"], name="api_posttag_post_id_2e06e1_idx"
                    )
                ],
            },
        ),
    ]
